### ISSUE TITLE
Credit?

### ISSUE THREAD

**Issue by polymeris** [eccentric-j/cljs-tui-template#5]
Hello,

as you can tell from [the initial commit](https://github.com/denisidoro/floki/commit/88fd66e75ba4770c0fc134948aa335bc4c81af3d#diff-0fff143854a4f5c0469a3819b978a483R20), floki is based on my [hello-react-blessed gist](https://gist.github.com/polymeris/5e117676b79a505fe777df17f181ca2e). Of course you have taken this to a whole other level, but would you mind crediting me for the original implementation/idea?

**Comment by jaidetree** [comment]
Thanks for the initial research! I’ll update the README, the demo app, and the source comments and docstrings. Should be able to get that up today.

**Comment by polymeris** [comment]
Thank you!

**Comment by jaidetree** [comment]
All set! I'll re-record the intro gif as well at a later date and time so the new blurb about your work is displayed. Thanks again.

**Comment by polymeris** [comment]
I see, even my "debug info" panel persisted into your implementation.
To be honest, I am flattered that this got so much traction.

How did you solve the issue of `console.log` messing with the rendering and instead redirecting logs to  the panel? Is my `(set! (.-log js/console) log-fn)` hack still buried somewhere?

**Comment by jaidetree** [comment]
Agreed, the response has been pretty positive! I'm sorry I didn't find out about your gist sooner though.

- [X] Update README.md
- [X] Update credits in demo
- [X] Update credits in gif recording
- [X] Update credits in debug box
- [X] Update credits in log-fn
- [X] Release new version to Clojars

Whew! I think that's everything.

**Comment by jaidetree** [comment]
Also, your log overrides also made their way into the codebase too:

https://github.com/eccentric-j/cljs-tui-template/blob/master/resources/leiningen/new/cljs_tui/env/dev/app.cljs#L37

The rest of the changes above can be seen here:
https://github.com/eccentric-j/cljs-tui-template/compare/dea00684aaa813c1f9d4df032b5cca703369eaac...6ad22eb0d069666a072c58709fc82e6f1a2ca8c3
