### ISSUE TITLE
Does this really need to depend on Java/Clojure?

### ISSUE THREAD

**Issue by divs1210** [eccentric-j/cljs-tui-template#7]
Seeing that ClojureScript is self hosted, is there a reason why this depends on Java?
I'm guessing it's currently because of the Clojure cli tools?

**Comment by jaidetree** [comment]
Great question! If you use this library and build a node app, it should run without java installed since it's compiled to JS. However, lein, lein-figwheel, figwheel-main, and shadow-cljs do depend on Java to run their tooling and pull in the clojurescript dependencies such as re-frame and reagent.

**Comment by divs1210** [comment]
Removing the JVM would be great, but this template is awesome anyways. 😄 
Thank you!
